<CATALOG>
<CD>
<TITLE>The Slow Rush</TITLE>
<ARTIST>Tame Impala</ARTIST>
<COUNTRY>AU</COUNTRY>
<COMPANY>Modular Recording</COMPANY>
<PRICE>13.99</PRICE>
<YEAR>2020</YEAR>
</CD>
<CD>
<TITLE>Certified Hitmaker</TITLE>
<ARTIST>Lil Mosey</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Interscope Records</COMPANY>
<PRICE>9.49</PRICE>
<YEAR>2020</YEAR>
</CD>
<CD>
<TITLE>We Love You Tecca</TITLE>
<ARTIST>Lil Tecca</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Republic Records</COMPANY>
<PRICE>12.59</PRICE>
<YEAR>2019</YEAR>
</CD>
<CD>
<TITLE>Die A Legend</TITLE>
<ARTIST>Polo G</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Colombia Records</COMPANY>
<PRICE>9.99</PRICE>
<YEAR>2019</YEAR>
</CD>
<CD>
<TITLE>KIRK</TITLE>
<ARTIST>DaBaby</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Interscope Records</COMPANY>
<PRICE>9.49</PRICE>
<YEAR>2019</YEAR>
</CD>
<CD>
<TITLE>I Made a Promise</TITLE>
<ARTIST>Lil Pete</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Public Housin</COMPANY>
<PRICE>11.49</PRICE>
<YEAR>2017</YEAR>
</CD>
<CD>
<TITLE>Victory Lap</TITLE>
<ARTIST>Nipsey Hussle</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Atlantic Recording</COMPANY>
<PRICE>11.38</PRICE>
<YEAR>2018</YEAR>
</CD>
<CD>
<TITLE>Gravity Pt.1</TITLE>
<ARTIST>Gryffin</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Darkroom/Geffen Records</COMPANY>
<PRICE>21.50</PRICE>
<YEAR>2018</YEAR>
</CD>
<CD>
<TITLE>Motion</TITLE>
<ARTIST>Calvin Harris</ARTIST>
<COUNTRY>UK</COUNTRY>
<COMPANY>Sony Music Entertainment UK</COMPANY>
<PRICE>12.00</PRICE>
<YEAR>2014</YEAR>
</CD>
<CD>
<TITLE>The Chronic</TITLE>
<ARTIST>Dr. Dre</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Wideawake- Death Row</COMPANY>
<PRICE>16.13</PRICE>
<YEAR>1992</YEAR>
</CD>
<CD>
<TITLE>Carnival</TITLE>
<ARTIST>Bryce Vine</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Sire Records</COMPANY>
<PRICE>7.99</PRICE>
<YEAR>2019</YEAR>
</CD>
<CD>
<TITLE>Night Circus</TITLE>
<ARTIST>Bryce Vine</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Sire Records</COMPANY>
<PRICE>3.99</PRICE>
<YEAR>2016</YEAR>
</CD>
<CD>
<TITLE>All American</TITLE>
<ARTIST>Hoodie Allen</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Hoodie Allen</COMPANY>
<PRICE>7.92</PRICE>
<YEAR>2012</YEAR>
</CD>
<CD>
<TITLE>Industry Plant</TITLE>
<ARTIST>Iann Dior</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Internet Money Records</COMPANY>
<PRICE>9.49</PRICE>
<YEAR>2019</YEAR>
</CD>
<CD>
<TITLE>The Days/ Nights</TITLE>
<ARTIST>Avicii</ARTIST>
<COUNTRY>SE</COUNTRY>
<COMPANY>Universal Music AB</COMPANY>
<PRICE>3.99</PRICE>
<YEAR>2014</YEAR>
</CD>
<CD>
<TITLE>Pharmacy</TITLE>
<ARTIST>Galantis</ARTIST>
<COUNTRY>SE</COUNTRY>
<COMPANY>Atlantic Recording</COMPANY>
<PRICE>13.99</PRICE>
<YEAR>2015</YEAR>
</CD>
<CD>
<TITLE>Church</TITLE>
<ARTIST>Galantis</ARTIST>
<COUNTRY>SE</COUNTRY>
<COMPANY>Atlantic Recording</COMPANY>
<PRICE>9.49</PRICE>
<YEAR>2020</YEAR>
</CD>
<CD>
<TITLE>Native</TITLE>
<ARTIST>One Republic</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Mosley Music/Interscope Records</COMPANY>
<PRICE>11.68</PRICE>
<YEAR>2014</YEAR>
</CD>
<CD>
<TITLE>Dazed and Confused EP</TITLE>
<ARTIST>Jake Miller</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Warner Records Inc.</COMPANY>
<PRICE>5.99</PRICE>
<YEAR>2014</YEAR>
</CD>
<CD>
<TITLE>A Romantic Comedy</TITLE>
<ARTIST>Huey Mack</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Huey Mack LLC</COMPANY>
<PRICE>9.49</PRICE>
<YEAR>2019</YEAR>
</CD>
<CD>
<TITLE>TMRW</TITLE>
<ARTIST>Luke Christopher</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>ByStorm Entertainment/ Sony Music Entertainment</COMPANY>
<PRICE>7.99</PRICE>
<YEAR>2015</YEAR>
</CD>
<CD>
<TITLE>Red Pills Blue (Deluxe)</TITLE>
<ARTIST>Maroon 5</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Interscope Records</COMPANY>
<PRICE>10.99</PRICE>
<YEAR>2017</YEAR>
</CD>
<CD>
<TITLE>10,000 Hours</TITLE>
<ARTIST>Dan + Shay</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Warner Music Nashville</COMPANY>
<PRICE>1.99</PRICE>
<YEAR>2019</YEAR>
</CD>
<CD>
<TITLE>Dan + Shay</TITLE>
<ARTIST>Dan + Shay</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Warner Music Nashville</COMPANY>
<PRICE>13.59</PRICE>
<YEAR>2018</YEAR>
</CD>
<CD>
<TITLE>Do It Again</TITLE>
<ARTIST>Pia Mia</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Interscope Records</COMPANY>
<PRICE>1.99</PRICE>
<YEAR>2015</YEAR>
</CD>
<CD>
<TITLE>#willpower(Deluxe)</TITLE>
<ARTIST>will.i.am</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Interscope Records</COMPANY>
<PRICE>11.49</PRICE>
<YEAR>2013</YEAR>
</CD>
</CATALOG>
